package com.javarush.island.bulanov.constants;

import com.javarush.island.bulanov.animals.Plant;
import com.javarush.island.bulanov.animals.herbivorous.*;
import com.javarush.island.bulanov.animals.predator.*;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.Map;

public class ProbabilityOfEating{
    public static final Map<Type, Map<Type, Integer>> probability = new HashMap<>(){{
        put(Wolf.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 10);
            put(Deer.class, 15);
            put(Rabbit.class, 60);
            put(Mouse.class, 80);
            put(Goat.class,60);
            put(Sheep.class, 70);
            put(WildBoar.class, 15);
            put(Buffalo.class, 10);
            put(Duck.class, 40);
            put(Caterpillar.class, 0);
            put(Plant.class, 0);
        }});
        put(BoaConstrictor.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 15);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 20);
            put(Mouse.class, 40);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 10);
            put(Caterpillar.class, 0);
            put(Plant.class, 0);
        }});
        put(Fox.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 70);
            put(Mouse.class, 90);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 60);
            put(Caterpillar.class, 40);
            put(Plant.class, 0);
        }});
        put(Bear.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 80);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 40);
            put(Deer.class, 80);
            put(Rabbit.class, 80);
            put(Mouse.class, 90);
            put(Goat.class,70);
            put(Sheep.class, 70);
            put(WildBoar.class, 50);
            put(Buffalo.class, 50);
            put(Duck.class, 20);
            put(Caterpillar.class, 10);
            put(Plant.class, 0);
        }});
        put(Eagle.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 10);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 90);
            put(Mouse.class, 90);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 80);
            put(Caterpillar.class, 0);
            put(Plant.class, 0);
        }});
        put(Horse.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 0);
            put(Mouse.class, 0);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 0);
            put(Caterpillar.class, 0);
            put(Plant.class, 100);
        }});
        put(Deer.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 0);
            put(Mouse.class, 0);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 0);
            put(Caterpillar.class, 0);
            put(Plant.class, 100);
        }});
        put(Rabbit.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 0);
            put(Mouse.class, 0);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 0);
            put(Caterpillar.class, 0);
            put(Plant.class, 100);
        }});
        put(Mouse.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 0);
            put(Mouse.class, 0);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 0);
            put(Caterpillar.class, 90);
            put(Plant.class, 100);
        }});
        put(Goat.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 0);
            put(Mouse.class, 0);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 0);
            put(Caterpillar.class, 0);
            put(Plant.class, 100);
        }});
        put(Sheep.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 0);
            put(Mouse.class, 0);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 0);
            put(Caterpillar.class, 0);
            put(Plant.class, 100);
        }});
        put(WildBoar.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 0);
            put(Mouse.class, 50);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 0);
            put(Caterpillar.class, 90);
            put(Plant.class, 100);
        }});
        put(Buffalo.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 0);
            put(Mouse.class, 0);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 0);
            put(Caterpillar.class, 0);
            put(Plant.class, 100);
        }});
        put(Duck.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 0);
            put(Mouse.class, 0);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 0);
            put(Caterpillar.class, 90);
            put(Plant.class, 100);
        }});
        put(Caterpillar.class, new HashMap<>(){{
            put(Wolf.class, 0);
            put(BoaConstrictor.class, 0);
            put(Fox.class, 0);
            put(Bear.class, 0);
            put(Eagle.class, 0);
            put(Horse.class, 0);
            put(Deer.class, 0);
            put(Rabbit.class, 0);
            put(Mouse.class, 0);
            put(Goat.class,0);
            put(Sheep.class, 0);
            put(WildBoar.class, 0);
            put(Buffalo.class, 0);
            put(Duck.class, 0);
            put(Caterpillar.class, 0);
            put(Plant.class, 100);
        }});
    }};

}
